--- 
- name: Call a role with delegate 
  hosts: all
  gather_facts: no
  vars:
    object_name: some_application # that is also a group name  
    object_type: application_server 
    action: start
  tasks:
    - name: Do something on all the servers
      debug:
        msg: "hello from all the servers"

    - name: call the common role on just one server
      include_role: 
        name: common
        apply:
          delegate_to: "{{ object_name }}"