--- 
- name: Call a role with delegate 
  hosts: all
  gather_facts: no
  vars:
    object_name: some_application # that is also a group name  
    object_type: application_server 
    action: start
  tasks:
    - name: call the common role
      import_role: 
        name: common
      delegate_to: "{{ groups['test'] }}"